apiVersion: v1
kind: Service
metadata:
  name: new-portfolio-service
  namespace: portfolio
spec:
  selector:
    app: new-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
