# postgres-values.yaml
global:
  postgresql:
    auth:
      username: sonar
      database: sonar
      existingSecret: sonarqube-postgres-secret
      # NB name of the key on the secret "sonarqube-postgres-secret" must be password for user sonar and postgres-password

primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
