postgresql:
  enabled: false

## Override JDBC values
## for external Databases
jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://postgres-sonarqube-postgresql.sonarqube.svc.cluster.local:5432/sonar"
  jdbcUsername: "sonar"
  jdbcSecretName: "sonarqube-postgres-secret"
  jdbcSecretPasswordKey: "password" # Key on secret sonarqube-postgres-secret

monitoringPasscode: "admin"

community:
  enabled: true
  buildNumber: "25.11.0.114957"

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "3Gi"
    cpu: "1"

ingress:
  enabled: false

# For HTTPS with API gateway
httproute:
  enabled: true
  gateway: envoy-gateway
  gatewayNamespace: envoy-gateway-system
  hostnames:
    - sonarqube.kouidri.fr
