apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n7-eportfolio
  name: n7-eportfolio
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n7-eportfolio
  strategy: {}
  template:
    metadata:
      labels:
        app: n7-eportfolio
    spec:
      containers:
      - image: yaniskouidri/n7-eportfolio:0.2-arm
        name: n7-eportfolio
        imagePullPolicy: Always
