# This file contains all properties used my the Minecraft server
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
  namespace: minecraft
data:
  VERSION: 1.21.8
  EULA: "TRUE"
  TYPE: "PAPER"
  ENABLE_RCON: "TRUE"
  BROADCAST_RCON_TO_OPS: "TRUE"
  DIFFICULTY: "normal"
  MODE: "creative"
  MOTD: "Bienvenue sur mon serveur Minecraft!"
  MAX_PLAYERS: "5"
  ONLINE_MODE: "TRUE"
  FORCE_GAMEMODE: "TRUE"
  ENABLE_WHITELIST: "TRUE"
  PLUGINS: |
    https://cdn.modrinth.com/data/1u6JkXh5/versions/3ISh7ADm/worldedit-bukkit-7.3.17.jar
    https://download.luckperms.net/1609/bukkit/loader/LuckPerms-Bukkit-5.5.20.jar
    https://cdn.modrinth.com/data/DKY9btbd/versions/PO4MKx7e/worldguard-bukkit-7.0.14-dist.jar
