apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        resources:
          limits:
            cpu: "1.5"
            memory: "1.5Gi"
        ports:
        - containerPort: 25565
        envFrom:
          - configMapRef:
              name: minecraft-server-config
        volumeMounts:
        - mountPath: /data  # Volume de données pour Minecraft
          name: minecraft-data
        - mountPath: /data/whitelist.json  # Montage de la whitelist
          name: whitelist-volume
          subPath: whitelist.json  # Monte uniquement le fichier whitelist.json

      volumes:
      - name: minecraft-data  # Volume persistant pour les données Minecraft
        persistentVolumeClaim:
          claimName: minecraft-pvc
      - name: whitelist-volume  # ConfigMap pour la whitelist
        configMap:
          name: minecraft-whitelist
