apiVersion: v1
kind: Service
metadata:
  name: my-first-website-service
  namespace: portfolio
spec:
  selector:
    app: my-first-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
