apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress
  namespace: portfolio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - www.kouidri.fr
      - kouidri.fr
      secretName: kouidri-tls
  rules:
  - host: www.kouidri.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: personal-website-service
            port:
              number: 80
  - host: kouidri.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: personal-website-service
            port:
              number: 80

