apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress
  namespace: portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: www.kouidri.test
    http:
      paths:
      - pathType: Prefix
        path: "/my-first-website/(.*)"
        backend:
          service:
            name: my-first-website-service
            port:
              number: 8080
      - pathType: Prefix
        path: "/(.*)"
        backend:
          service:
            name: personal-website-service
            port:
              number: 80
