apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: portfolio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/private-key-algorithm: "ECDSA"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - www.kouidri.fr
      - beta.kouidri.fr
      - eportfolio.kouidri.fr
      secretName: subdomain-kouidri-tls
  rules:
  - host: beta.kouidri.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: new-portfolio-service
            port:
              number: 80
  - host: www.kouidri.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: personal-website-service
            port:
              number: 80
  - host: eportfolio.kouidri.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: n7-eportfolio-service
            port:
              number: 80

