apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-server-config
  namespace: immich
data:
  # Immich
  TZ: "Europe/Paris"
  IMMICH_VERSION: "2"
  # Redis
  REDIS_PORT: "6379"
  REDIS_HOSTNAME: redis
  # Postgres
  DB_HOSTNAME: postgres
  DB_PORT: "5432"
