apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-server-config
  namespace: immich
data:
  TZ: "Europe/Paris"
  IMMICH_VERSION: "2"
  REDIS_PORT: "6379"
  DB_HOSTNAME: postgres
  DB_PORT: "5432"
