apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Paris"
  SERVERURL: "kouidri.fr"
  SERVERPORT: "51820"
  PEERS: "5"
  PEERDNS: "auto"
  INTERNAL_SUBNET: "10.13.13.0"

