apiVersion: v1
kind: Service
metadata:
  name: n7-eportfolio-service
  namespace: portfolio
spec:
  selector:
    app: n7-eportfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
