apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db-config
  namespace: immich
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "immich"
  POSTGRES_INITDB_ARGS: "--data-checksums"
  # DB_STORAGE_TYPE: "HDD"  # DÃ©commente si besoin
