# Redirection HTTP -> HTTPS for all HTTP listners
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-filter-redirect
  namespace: portfolio
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
# Portfolio frontend and backend
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-www-kouidri-fr
  namespace: portfolio
spec:
  hostnames:
    - www.kouidri.fr
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: https
  rules:
    - backendRefs:
        - name: frontend
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: backend
          port: 3001
      matches:
        - path:
            type: PathPrefix
            value: /api/
    - backendRefs:
        - name: backend
          port: 3001
      matches:
        - path:
            type: PathPrefix
            value: /data/
---
# CMS
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-cms-kouidri-fr
  namespace: portfolio
spec:
  hostnames:
    - cms.kouidri.fr
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: https
  rules:
    - backendRefs:
        - name: strapi
          port: 1337
      matches:
        - path:
            type: PathPrefix
            value: /
---
# https://kouidri.fr -> https://www.kouidri.fr
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kouidri-to-www-redirect
  namespace: portfolio
spec:
  hostnames:
    - kouidri.fr
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: https
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            hostname: www.kouidri.fr
